// <auto-generated />
using System;
using Gram.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gram.Infrastructure.Migrations.AuditServiceMigrations
{
    [DbContext(typeof(AuditService))]
    partial class AuditServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gram.Infrastructure.Services.AuditService+AuditDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditLogId");

                    b.Property<string>("NewValue")
                        .IsRequired();

                    b.Property<string>("OldValue")
                        .IsRequired();

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId")
                        .HasName("IX_AuditDetail_AuditLog");

                    b.ToTable("AuditDetail","Audit");
                });

            modelBuilder.Entity("Gram.Infrastructure.Services.AuditService+AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int>("EntityId");

                    b.Property<string>("EntityState")
                        .IsFixedLength(true)
                        .HasMaxLength(1);

                    b.Property<DateTime>("RowModifyDate");

                    b.Property<string>("RowModifyUser")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("AuditLog","Audit");
                });

            modelBuilder.Entity("Gram.Infrastructure.Services.AuditService+AuditDetail", b =>
                {
                    b.HasOne("Gram.Infrastructure.Services.AuditService+AuditLog", "AuditLog")
                        .WithMany("AuditDetails")
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
